# Website configuration
title: SS-NES landing page
description: >-
  Sustainable software practices (software management, software quality, FAIR software,
  and software preservation) is crucial for the reusability and long-term viability of
  research software (scripts, code, tools, and digital methodologies) particularly in the
  Natural Sciences & Engineering (NES) domain.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
theme: https://github.com/SS-NES/jekyll-theme-ss-nes
